# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support
        ref: actions

    - name: Install -pip
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install 'pylint<2.5' python-coveralls 'coverage>=4.4,<5.0'

    - name: Install Spinnaker Dependencies
      uses: ./.github/actions/checkout-spinn-deps
      with:
        repositories: >
          SpiNNUtils SpiNNMachine SpiNNMan PACMAN DataSpecification spalloc 
          SpiNNFrontEndCommon
        install: true
        preinstall: ${{ matrix.python-version == 2.7 }}

    - name: Preinstall requirements (2.7 Only)
      if: matrix.python-version == 2.7
      run: pip install -r requirements.txt

    - name: Setup
      run: python setup.py develop

    - name: Install requirements-test
      run: pip install -r requirements-test.txt

    - name: Create a spynnaker.cfg
      uses: ./.github/actions/configure-spynnaker
      with:
        board-address: spinn-4.cs.man.ac.uk

    - name: Test with pytest
      uses: ./.github/actions/pytest
      with:
        tests: unittests
        coverage: ${{ matrix.python-version == 3.6 }}
        cover-packages: spynnaker
        coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Lint with flake8
      run: flake8 spynnaker unittests

    - name: Lint with pylint
      # Broken in 2.7 as it can not find data_specification.exceptions
      if: matrix.python-version != 2.7
      uses: ./.github/actions/pylint
      with: 
        package: spynnaker

    - name: Run rat copyright enforcement
      if: matrix.python-version == 3.6
      uses: ./support/.github/actions/check-copyrights

    - name: Build documentation with sphinx
      uses: ./.github/actions/sphinx
      with:
        directory: doc/source
